env {
  job.mode = "STREAMING"
  job.name = "DataSync"
  parallelism = 1
  checkpoint.interval = 10000
}

source {
  MySQL-CDC {
    base-url = "jdbc:mysql://127.0.0.1:3306/seatunnel_prod?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai"
    username = "root"
    password = "qwer123."
    table-names = ["seatunnel_prod.testtable"]
    startup.mode = "initial"
    server-id = "100-200"
  }
}

transform {
  FieldMapper {
    table_fields {
      "id" = "id"
    }
  }}
}}

sink {
  Jdbc {
    url = "jdbc:mysql://127.0.0.1:3306/target?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "root"
    password = "qwer123."
    database = "target"
    table = "test_2"
    batch_size = 100
    generate_sink_sql = true
    save_mode = "overwrite"
    primary_keys = ["id"]
  }
}