# ============================================
# SeaTunnel 配置（自动生成）
# 生成时间：2026-05-15 16:10:01
# ============================================

env {
  job.mode = "BATCH"
  job.name = "MySQL_to_MySQL_Sync"
  parallelism = 1
}

source {
  Jdbc {
    url = "jdbc:mysql://127.0.0.1:3306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "root"
    password = "qwer123."
    query = "SELECT "user_id" AS "id", "username" AS "username", "email" AS "email", "age" AS "age", "city" AS "city", "status" AS "status", "created_at" AS "created_at" FROM `test`.`users`"
  }
}

sink {
  Jdbc {
    url = "jdbc:mysql://127.0.0.1:3306/target?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "root"
    password = "qwer123."
    database = "target"
    table = "test_2"
    batch_size = 100
    generate_sink_sql = true
    save_mode = "upsert"
    primary_keys = "id"
  }
}
